# Site settings
title: Thesis Report
email: niene.boeijen@wur.nl
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nieneb.github.io/ThesisReport/" # the base hostname & protocol for your site
twitter_username: BNiene
github_username:  NieneB

# Build settings
markdown: kramdown
