# Site settings
title: Msc Thesis Report 
email: niene.boeijen@wur.nl
description: > # this means to ignore newlines until "baseurl:"
  This is the report for my Msc thesis for the studies; Geo-Information Science & Remote Sensing. Wageningen University.
baseurl: "/ThesisReport" # the subpath of your site, e.g. /blog/
url: "http://nieneb.github.io" # the base hostname & protocol for your site
twitter_username: BNiene
github_username:  NieneB

# Build settings
markdown: kramdown
